# Generated by Django 5.0.6 on 2025-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_marks', models.IntegerField(choices=[(60, '60'), (50, '50'), (30, '30')])),
                ('obtained_marks', models.IntegerField()),
            ],
        ),
    ]
